apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: code-engine-cd-pipeline
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com

    - name: source-region
      description: region of source code-engine project
    - name: source-resource-group
      description: resource group for source code-engine-project
    - name: source-code-engine-project
      description: Code Engine project source for fetching component information
    - name: source-app-name
      description: source application name
    - name: source-app-revision
      description: revision of the source application
      default: ""

    - name: region
      description: region of application deployment
    - name: resource-group
      description: resource group for the application deployment
    - name: code-engine-project
      description: Code Engine project for the application deployment

    - name: deployment-type
      description:  Specifies the type of deployment. Valid values are 'application' and 'job'. 
      default: "application"

    - name: app-name
      description: application name

    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"

    - name: env-from-configmaps
      description: semi-colon separated list of configmaps to set environment variables from
      default: ""
    - name: env-from-secrets
      description: semi-colon separated list of secrets to set environment variables from
      default: ""
    - name: suffix-for-cd-auto-managed-configuration-resources
      description: suffix for secret or configmap created based on CD environment properties
      default: ""
    - name: remove-unspecified-references-to-configuration-resources
      description: remove references to unspecified configuration resources (configmap/secret) references (pulled from env-from-configmaps, env-from-secrets along with auto-managed by CD)
      default: "false"

    - name: cpu
      description: the amount of vCPU set for each instance of the application or job
      default: "0.25"
    - name: memory
      description: the amount of memory set for each instance of the application or job
      default: "0.5G"
    - name: ephemeral-storage
      description: the amount of ephemeral storage to set for each instance of the application or job
      default: "0.4G"
    - name: app-max-scale
      description: maximum scale of the Code Engine application
      default: "1"
    - name: app-min-scale
      description: minimum scale of the Code Engine application
      default: "0"
    - name: app-port
      description: port where the application is listening
      default: "8080"
    - name: app-visibility
      description: the visibility for the application. Valid values are 'public', 'private' and 'project'.
      default: "public"
    - name: app-concurrency
      description: the maximum number of requests that can be processed concurrently per instance. 
      default: "100"
    - name: service-bindings
      description: JSON object of a map of names to services instances to be bound to the application
      default: "{}"

      # For health task
    - name: app-health-endpoint
      description: application health endpoint, e.g. /health
      default: ""
    - name: app-deployment-timeout
      description: maximum timeout for the application deployment.
      default: "300"
        
    # Job specific configuration
    - name: job-instances
      description: Specifies the number of instances that are used for runs of the job. When you use this option, the system converts to array indices. For example, if you specify 'instances' of 5, the system converts to 'array-indices' of '0 - 4'
      default: "1"
    - name: job-maxexecutiontime
      description: The maximum execution time in seconds for runs of the job. 
      default: "7200"
    - name: job-retrylimit
      description: The number of times to rerun an instance of the job before the job is marked as failed.
      default: "3"

    # DOI
    - name: doi-environment
      description: the environment for DOI
      default: "prod"

  workspaces:
    - name: pipeline-ws
  tasks:
    - name: fetch-component-information
      taskRef:
        name: fetch-component-information
      params:
        - name: component-name
          value: $(params.source-app-name)
        - name: deployment-type
          value: $(params.deployment-type)
        - name: application-revision
          value: $(params.source-app-revision)
        - name: region
          value: $(params.source-region)
        - name: resource-group
          value: $(params.source-resource-group)
        - name: code-engine-project
          value: $(params.source-code-engine-project)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: extract-doi-enablement
      taskRef:
        name: toolchain-extract-value
      params:
        # count the number of service in the toolchain that are DevopsInsights
        - name: expression
          value: 'reduce .services[] as $service (0; if $service.service_id=="draservicebroker" then .+1 else . end)'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: deploy-component
      taskRef:
        name: deploy-to-code-engine
      runAfter: [fetch-component-information]
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: shuttle-properties-file
          value: ""
        - name: app-name
          value: $(params.app-name)
        - name: region
          value: $(params.region)
        - name: resource-group
          value: $(params.resource-group)
        - name: code-engine-project
          value: $(params.code-engine-project)
        - name: service-bindings
          value: $(params.service-bindings)
        - name: env-from-configmaps
          value: $(params.env-from-configmaps)
        - name: env-from-secrets
          value: $(params.env-from-secrets)
        - name: suffix-for-cd-auto-managed-configuration-resources
          value: $(params.suffix-for-cd-auto-managed-configuration-resources)
        - name: remove-unspecified-references-to-configuration-resources
          value: $(params.remove-unspecified-references-to-configuration-resources)
        - name: cpu
          value: $(params.cpu)
        - name: app-max-scale
          value: $(params.app-max-scale)
        - name: memory
          value: $(params.memory)
        - name: ephemeral-storage
          value: $(params.ephemeral-storage)
        - name: app-min-scale
          value: $(params.app-min-scale)
        - name: app-port
          value: $(params.app-port)
        - name: app-visibility
          value: $(params.app-visibility)
        - name: app-concurrency
          value: $(params.app-concurrency)
        - name: image-repository
          value: $(tasks.fetch-component-information.results.image-repository)
        - name: image-tags
          value: $(tasks.fetch-component-information.results.image-tag)
        - name: image-pull-secret
          value: $(tasks.fetch-component-information.results.image-pull-secret)
        - name: image-pull-secret-kind
          value: $(tasks.fetch-component-information.results.image-pull-secret-kind)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: app-deployment-timeout
          value: $(params.app-deployment-timeout)
        - name: deployment-type
          value: $(params.deployment-type)
        - name: job-instances
          value: $(params.job-instances)
        - name: job-maxexecutiontime
          value: $(params.job-maxexecutiontime)
        - name: job-retrylimit
          value: $(params.job-retrylimit)
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: publish-deployable-task
      runAfter: [deploy-component]
      taskRef:
        name: publish-code-engine-deployable-mapping
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: app-name
          value: $(params.app-name)
        - name: region
          value: $(params.region)
        - name: resource-group
          value: $(params.resource-group)
        - name: code-engine-project
          value: $(params.code-engine-project)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: deployment-type
          value: $(params.deployment-type)
    - name: check-health
      taskRef:
        name: check-health
      runAfter: [deploy-component]
      params:
        - name: app-hostname
          value: $(tasks.deploy-component.results.app-url)
        - name: app-health-endpoint
          value: $(params.app-health-endpoint)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
  finally:
    - name: publish-fail-doi-deployrecord
      taskRef:
        name: doi-publish-deployrecord
      when:
        - input: $(tasks.extract-doi-enablement.results.extracted-value)
          operator: in
          values: ["1"]
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      params:
        - name: toolchain-apikey-secret-key
          value: "toolchain-apikey"
        - name: build-number
          value: "$(tasks.fetch-component-information.results.doi-build-number)"
        - name: app-name
          value: "$(tasks.fetch-component-information.results.doi-logical-app-name)"
        - name: environment
          value: $(params.doi-environment)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: deploy-status
          value: "fail"
    - name: publish-pass-doi-deployrecord
      taskRef:
        name: doi-publish-deployrecord
      when:
        - input: $(tasks.extract-doi-enablement.results.extracted-value)
          operator: in
          values: ["1"]
        - input: $(tasks.status)
          operator: in
          values: ["Succeeded", "Completed"]
      params:
        - name: toolchain-apikey-secret-key
          value: "toolchain-apikey"
        - name: build-number
          value: "$(tasks.fetch-component-information.results.doi-build-number)"
        - name: app-name
          value: "$(tasks.fetch-component-information.results.doi-logical-app-name)"
        - name: app-url
          value: $(tasks.deploy-component.results.app-url)
        - name: environment
          value: $(params.doi-environment)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: deploy-status
          value: "pass"
